[colors.bright]
black = "0x709080"
blue = "0x94BFF3"
cyan = "0x93E0E3"
green = "0x72D5A3"
magenta = "0xEC93D3"
red = "0xDCA3A3"
white = "0xFFFFFF"
yellow = "0xF0DFAF"

[colors.normal]
black = "0x709080"
blue = "0x94BFF3"
cyan = "0x93E0E3"
green = "0x72D5A3"
magenta = "0xEC93D3"
red = "0xDCA3A3"
white = "0xFFFFFF"
yellow = "0xF0DFAF"

[colors.primary]
background = "0x2C2C2C"
foreground = "0xDCDCCC"

[font]
size = 14.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"
